global using Common.DTOs;
global using Membership.Database.Extensions;
global using Membership.Database.Services;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Common.HttpClients;
global using Membership.Database.Contexts;
global using Membership.Database.Entities;
global using Microsoft.EntityFrameworkCore;
